# Generated by Django 4.2 on 2023-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
