# Generated by Django 4.2 on 2023-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
